import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar/Navbar";
import ClientOnly from "@/components/shared/ClientOnly";
import Sprovider from "@/providers/SessionProvider";
import RegisterModel from "@/models/RegisterModel";
import ToasterProvider from "@/providers/ToasterProvider";
import LogInModel from "@/models/LogInModel";
import { getCurrentUser } from "@/actions/getCurrentUser";

import RentModel from "@/models/RentModel";
import SearchModel from "@/models/SearchModel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Airbnb",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const currentUser = await getCurrentUser();
	return (
		<html lang="en">
			<Sprovider>
				<body className={inter.className}>
					<ClientOnly>
						<ToasterProvider />
						<RegisterModel />
						<RentModel />
						<SearchModel />
						<LogInModel />
						<Navbar currentUser={currentUser} />
					</ClientOnly>
					<div className="pb-20 pt-28">{children}</div>
				</body>
			</Sprovider>
		</html>
	);
}
